services:
  Gate:
    image: Rexa/Gate:latest
    # for situations, you don't have access to docker hub use ðŸ‘‡
    # image: ghcr.io/Rexa/Gate:latest
    restart: always
    network_mode: host

    environment:
      SERVICE_PORT: 62050
      SERVICE_PROTOCOL: "grpc"

      SSL_CERT_FILE: "/var/lib/pg-Gate/certs/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/pg-Gate/certs/ssl_key.pem"
      # api key must be a valid uuid (you can use any version you want)
      # API_KEY: xxxxxxxx-yyyy-zzzz-mmmm-aaaaaaaaaaa

      GENERATED_CONFIG_PATH: "/var/lib/pg-Gate/generated"

    volumes:
      - /var/lib/pg-Gate:/var/lib/pg-Gate
